#!/bin/bash

function ctrl_c {
    echo "** Trapped CTRL-C"
    exit
}

trap ctrl_c INT TERM EXIT


while true; do

    ghc $1.hs && $1

    echo ""
    inotifywait -qr -e modify -e create -e move -e delete $1.hs
done
